version: "3.3"

services:
  dev_machine:
    container_name: dev_container
    build: .
    tty: true
    ports:
      - "2222:22"
      - "28080:8080"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - local_net
    volumes:
      - ${PWD}/projects:/root/projects
      - ${PWD}/vscode-server:/root/.vscode-server
  postgres:
    container_name: dev_pg
    image: postgres:14.1-alpine
    expose:
      - 5432
    ports:
      - "25432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    command: postgres -c listen_addresses='*'
    networks:
      - local_net
